/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated at: 2025-10-16T22:14:55.787Z
 * 
 * This file is automatically generated during the build process.
 * It contains build-specific information like build number and git commit.
 */

export interface BuildInfo {
  buildNumber: string;
  buildDate: string;
  gitCommit: string;
  gitBranch: string;
  timestamp: number;
}

export const buildInfo: BuildInfo = {
  "buildNumber": "20251016221455",
  "buildDate": "2025-10-16T22:14:55.787Z",
  "gitCommit": "061b015",
  "gitBranch": "main",
  "timestamp": 1760652895787
};

// Human-readable formats
export const getBuildNumberShort = (): string => {
  // Format: YYMMDD-HHmm
  const bn = buildInfo.buildNumber;
  return `${bn.slice(2, 8)}-${bn.slice(8, 12)}`;
};

export const getBuildDateFormatted = (): string => {
  return new Date(buildInfo.buildDate).toLocaleString();
};

export const getGitInfo = (): string => {
  return `${buildInfo.gitBranch}@${buildInfo.gitCommit}`;
};
